# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1798, 904)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setLayoutDirection(QtCore.Qt.LeftToRight)
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setAnimated(False)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setDockNestingEnabled(False)
        MainWindow.setDockOptions(QtWidgets.QMainWindow.AllowTabbedDocks)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tableWidget_ply = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_ply.setMinimumSize(QtCore.QSize(420, 200))
        self.tableWidget_ply.setMaximumSize(QtCore.QSize(420, 200))
        self.tableWidget_ply.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_ply.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget_ply.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget_ply.setTabKeyNavigation(False)
        self.tableWidget_ply.setProperty("showDropIndicator", False)
        self.tableWidget_ply.setDragDropOverwriteMode(False)
        self.tableWidget_ply.setAlternatingRowColors(True)
        self.tableWidget_ply.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableWidget_ply.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget_ply.setObjectName("tableWidget_ply")
        self.tableWidget_ply.setColumnCount(4)
        self.tableWidget_ply.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ply.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ply.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ply.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_ply.setHorizontalHeaderItem(3, item)
        self.tableWidget_ply.horizontalHeader().setDefaultSectionSize(95)
        self.tableWidget_ply.verticalHeader().setDefaultSectionSize(20)
        self.tableWidget_ply.verticalHeader().setMinimumSectionSize(20)
        self.gridLayout_4.addWidget(self.tableWidget_ply, 0, 0, 1, 1)
        self.tableView_points = QtWidgets.QTableView(self.centralwidget)
        self.tableView_points.setEnabled(True)
        self.tableView_points.setMinimumSize(QtCore.QSize(595, 200))
        self.tableView_points.setMaximumSize(QtCore.QSize(595, 200))
        self.tableView_points.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableView_points.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableView_points.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableView_points.setAlternatingRowColors(True)
        self.tableView_points.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableView_points.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableView_points.setSortingEnabled(True)
        self.tableView_points.setWordWrap(False)
        self.tableView_points.setCornerButtonEnabled(False)
        self.tableView_points.setObjectName("tableView_points")
        self.tableView_points.horizontalHeader().setCascadingSectionResizes(False)
        self.tableView_points.horizontalHeader().setDefaultSectionSize(80)
        self.tableView_points.horizontalHeader().setMinimumSectionSize(80)
        self.tableView_points.horizontalHeader().setStretchLastSection(False)
        self.tableView_points.verticalHeader().setCascadingSectionResizes(False)
        self.tableView_points.verticalHeader().setDefaultSectionSize(20)
        self.tableView_points.verticalHeader().setMinimumSectionSize(20)
        self.gridLayout_4.addWidget(self.tableView_points, 0, 1, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.crit_cbbox = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.crit_cbbox.sizePolicy().hasHeightForWidth())
        self.crit_cbbox.setSizePolicy(sizePolicy)
        self.crit_cbbox.setMinimumSize(QtCore.QSize(150, 20))
        self.crit_cbbox.setMaximumSize(QtCore.QSize(150, 20))
        self.crit_cbbox.setObjectName("crit_cbbox")
        self.crit_cbbox.addItem("")
        self.crit_cbbox.addItem("")
        self.crit_cbbox.addItem("")
        self.crit_cbbox.addItem("")
        self.horizontalLayout.addWidget(self.crit_cbbox)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setMinimumSize(QtCore.QSize(0, 20))
        self.line.setMaximumSize(QtCore.QSize(10, 20))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.minLabel = QtWidgets.QLabel(self.centralwidget)
        self.minLabel.setMinimumSize(QtCore.QSize(30, 20))
        self.minLabel.setMaximumSize(QtCore.QSize(30, 20))
        self.minLabel.setObjectName("minLabel")
        self.horizontalLayout.addWidget(self.minLabel)
        self.minscaleLE = QtWidgets.QLineEdit(self.centralwidget)
        self.minscaleLE.setMinimumSize(QtCore.QSize(80, 20))
        self.minscaleLE.setMaximumSize(QtCore.QSize(50, 20))
        self.minscaleLE.setObjectName("minscaleLE")
        self.horizontalLayout.addWidget(self.minscaleLE)
        self.maxLabel = QtWidgets.QLabel(self.centralwidget)
        self.maxLabel.setMinimumSize(QtCore.QSize(30, 20))
        self.maxLabel.setMaximumSize(QtCore.QSize(30, 20))
        self.maxLabel.setObjectName("maxLabel")
        self.horizontalLayout.addWidget(self.maxLabel)
        self.maxscaleLE = QtWidgets.QLineEdit(self.centralwidget)
        self.maxscaleLE.setMinimumSize(QtCore.QSize(80, 20))
        self.maxscaleLE.setMaximumSize(QtCore.QSize(80, 20))
        self.maxscaleLE.setObjectName("maxscaleLE")
        self.horizontalLayout.addWidget(self.maxscaleLE)
        self.scaleButton = QtWidgets.QPushButton(self.centralwidget)
        self.scaleButton.setMinimumSize(QtCore.QSize(80, 23))
        self.scaleButton.setMaximumSize(QtCore.QSize(80, 23))
        self.scaleButton.setObjectName("scaleButton")
        self.horizontalLayout.addWidget(self.scaleButton)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(500, 170))
        self.frame.setMaximumSize(QtCore.QSize(500, 170))
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setLineWidth(1)
        self.frame.setMidLineWidth(0)
        self.frame.setObjectName("frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setHorizontalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.mpl_widget = Mplwidget(self.frame)
        self.mpl_widget.setMinimumSize(QtCore.QSize(500, 170))
        self.mpl_widget.setMaximumSize(QtCore.QSize(500, 170))
        self.mpl_widget.setObjectName("mpl_widget")
        self.gridLayout_2.addWidget(self.mpl_widget, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 1, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 2, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 3, 1, 1)
        self.viewer_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewer_frame.sizePolicy().hasHeightForWidth())
        self.viewer_frame.setSizePolicy(sizePolicy)
        self.viewer_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.viewer_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.viewer_frame.setObjectName("viewer_frame")
        self.gridLayout = QtWidgets.QGridLayout(self.viewer_frame)
        self.gridLayout.setObjectName("gridLayout")
        self.gridLayout_4.addWidget(self.viewer_frame, 1, 0, 1, 4)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Post Processing Tool"))
        item = self.tableWidget_ply.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Ply"))
        item = self.tableWidget_ply.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Max Tsai-Hill"))
        item = self.tableWidget_ply.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Max Tsai-Wu"))
        item = self.tableWidget_ply.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Max Von Mises"))
        self.crit_cbbox.setItemText(0, _translate("MainWindow", "Tsai-Hill"))
        self.crit_cbbox.setItemText(1, _translate("MainWindow", "Tsai-Wu"))
        self.crit_cbbox.setItemText(2, _translate("MainWindow", "Von Mises"))
        self.crit_cbbox.setItemText(3, _translate("MainWindow", "Déplacements"))
        self.minLabel.setText(_translate("MainWindow", "min :"))
        self.maxLabel.setText(_translate("MainWindow", "max :"))
        self.scaleButton.setText(_translate("MainWindow", "Scale"))

from main import Mplwidget
